import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  ForbiddenException,
  Get,
  Injectable,
  Logger,
  Param,
  Patch,
  Post,
  Query,
  UseGuards,
} from "@nestjs/common";
import { InjectQueue } from "@nestjs/bullmq";
import type { Queue } from "bullmq";
import {
  EnrollmentStatus,
  NotificationType,
  Prisma,
  ReportCommentType,
  TermReportCardStatus,
  TermReportCardType,
} from "@prisma/client";
import { QUEUE_NAMES, type ReportCardGenerationJob } from "@school/types";
import { PrismaService } from "../prisma/prisma.service";
import { hashToken } from "../common/crypto/token";
import { JwtAuthGuard } from "../auth/jwt-auth.guard";
import { PoliciesGuard } from "../casl/policies.guard";
import { CheckPolicies } from "../casl/check-policies.decorator";
import { CurrentUser } from "../auth/current-user.decorator";
import type { RequestUser } from "../auth/jwt.strategy";
import { StaffAssignmentService } from "../staff-assignments/staff-assignment";
import { NotificationService } from "../notifications/notification";
import { GenerateTermReportCardDto } from "./dto/generate-term-report-card.dto";
import { GenerateClassReportCardsDto } from "./dto/generate-class-report-cards.dto";

interface ClassReadinessEntry {
  studentId: string;
  studentName: string;
  ready: boolean;
  missing: string[];
}

// Same "{ClassLevel.name} {ClassArm.name}" display format as
// academic-structure/class-arm.ts's own `withDisplayName` — duplicated
// rather than imported for the same module-boundary reason documented in
// staff-assignments/staff-assignment.ts.
function withStudentClassArmDisplayName<
  T extends { student: { currentClass: { name: string; classLevel: { name: string } } | null } },
>(
  card: T,
): T & { student: T["student"] & { currentClass: (T["student"]["currentClass"] & { displayName: string }) | null } } {
  return {
    ...card,
    student: {
      ...card.student,
      currentClass: card.student.currentClass
        ? {
            ...card.student.currentClass,
            displayName: `${card.student.currentClass.classLevel.name} ${card.student.currentClass.name}`,
          }
        : null,
    },
  };
}

@Injectable()
export class TermReportCardService {
  private readonly logger = new Logger(TermReportCardService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly staffAssignments: StaffAssignmentService,
    @InjectQueue(QUEUE_NAMES.REPORT_CARD_GENERATION) private readonly reportCardQueue: Queue<ReportCardGenerationJob>,
    private readonly notifications: NotificationService,
  ) {}

  /** Same "never let a notification failure fail the real write" contract as DiscountRequestService.notifySafely. */
  private async notifySafely(recipientUserId: string, type: NotificationType, vars: Record<string, string | number>) {
    try {
      await this.notifications.notify(recipientUserId, type, vars);
    } catch (error) {
      this.logger.warn(`Failed to notify ${recipientUserId} of ${type}: ${String(error)}`);
    }
  }

  /**
   * PRD FR4.7/§3.6: Admin-initiated for v1 — not auto-triggered when all
   * required pieces happen to become ready, which is simpler and safer.
   * Generation itself always succeeds (renders whatever exists); the
   * completeness gate lives in publish(), not here, so Admin can preview a
   * still-incomplete card before every piece is in.
   */
  async generateFullTerm(dto: GenerateTermReportCardDto, userId: string) {
    const reportCard = await this.prisma.termReportCard.upsert({
      where: {
        studentId_termId_reportType: { studentId: dto.studentId, termId: dto.termId, reportType: TermReportCardType.FULL_TERM },
      },
      create: {
        studentId: dto.studentId,
        termId: dto.termId,
        reportType: TermReportCardType.FULL_TERM,
        status: TermReportCardStatus.GENERATING,
        generatedByUserId: userId,
      },
      update: { status: TermReportCardStatus.GENERATING, generatedByUserId: userId },
    });

    await this.reportCardQueue.add("generate", {
      studentId: dto.studentId,
      termId: dto.termId,
      reportType: "FULL_TERM",
    });

    // Returned so the response body isn't empty — an empty 201 body made
    // apiFetch's res.json() throw on the frontend, which read as a failure
    // even though generation had actually been queued successfully.
    return reportCard;
  }

  /**
   * Re-runs generation for an existing card using its own reportType/
   * studentId/termId — unlike generateFullTerm (which only ever creates/
   * refreshes a FULL_TERM row), this covers MID_TERM cards too, since a
   * stale MID_TERM report (SubjectTermResultService.recomputeForStudentSubjectTerm
   * flagging it after a late opt-in) has no other manual regeneration path —
   * MID_TERM is otherwise only ever generated by the worker's sweep.
   */
  async regenerate(id: string) {
    const reportCard = await this.prisma.termReportCard.findUniqueOrThrow({ where: { id } });
    const updated = await this.prisma.termReportCard.update({
      where: { id },
      data: { status: TermReportCardStatus.GENERATING },
    });
    await this.reportCardQueue.add("generate", {
      studentId: reportCard.studentId,
      termId: reportCard.termId,
      reportType: reportCard.reportType,
    });
    return updated;
  }

  async publish(id: string) {
    const reportCard = await this.prisma.termReportCard.findUniqueOrThrow({
      where: { id },
      include: { student: { include: { user: true } }, term: true },
    });
    // MID_TERM's gate is scores-only (no comments/skills) — READY just means
    // the PDF finished generating. FULL_TERM additionally requires every
    // piece FR4.7 lists, checked here rather than at generation time.
    if (reportCard.status !== TermReportCardStatus.READY) {
      throw new BadRequestException(`Cannot publish a report card with status ${reportCard.status}`);
    }
    if (reportCard.reportType === TermReportCardType.FULL_TERM) {
      await this.assertFullTermPublishGate(reportCard.studentId, reportCard.termId);
    }
    const updated = await this.prisma.termReportCard.update({
      where: { id },
      data: { status: TermReportCardStatus.PUBLISHED, publishedAt: new Date() },
    });

    if (reportCard.reportType === TermReportCardType.FULL_TERM) {
      const guardians = await this.prisma.studentGuardian.findMany({
        where: { studentId: reportCard.studentId },
        include: { parent: true },
      });
      const studentName = `${reportCard.student.user.firstName} ${reportCard.student.user.lastName}`;
      for (const guardian of guardians) {
        await this.notifySafely(guardian.parent.userId, "REPORT_CARD_PUBLISHED", {
          studentName,
          termName: reportCard.term.name,
        });
      }
    }

    return updated;
  }

  private async assertFullTermPublishGate(studentId: string, termId: string): Promise<void> {
    const student = await this.prisma.studentProfile.findUniqueOrThrow({
      where: { id: studentId },
      include: { currentClass: true },
    });
    if (!student.currentClass) {
      throw new BadRequestException("Student has no current class — cannot publish a full-term report card");
    }
    const term = await this.prisma.term.findUniqueOrThrow({ where: { id: termId } });

    const enrollments = await this.prisma.studentSubjectEnrollment.findMany({
      where: { studentId, classArmId: student.currentClass.id, termId, status: EnrollmentStatus.ACTIVE },
    });
    const results = await this.prisma.subjectTermResult.findMany({ where: { studentId, termId } });
    const missingSubjects = enrollments.filter((e) => !results.some((r) => r.subjectId === e.subjectId));
    if (missingSubjects.length > 0) {
      throw new BadRequestException(
        `Missing SubjectTermResult for ${missingSubjects.length} actively-enrolled subject(s)`,
      );
    }

    const activeSkillItems = await this.prisma.skillAssessmentItem.findMany({
      where: { academicSessionId: term.academicSessionId, isActive: true },
    });
    const ratings = await this.prisma.skillRating.findMany({ where: { studentId, termId } });
    const missingSkills = activeSkillItems.filter((item) => !ratings.some((r) => r.skillAssessmentItemId === item.id));
    if (missingSkills.length > 0) {
      throw new BadRequestException(`Missing SkillRating for ${missingSkills.length} active skill assessment item(s)`);
    }

    const classTeacherComment = await this.prisma.reportComment.findFirst({
      where: { studentId, termId, commentType: ReportCommentType.CLASS_TEACHER },
    });
    if (!classTeacherComment) {
      throw new BadRequestException("Missing CLASS_TEACHER comment");
    }

    const principalComment = await this.prisma.reportComment.findFirst({
      where: { studentId, termId, commentType: ReportCommentType.PRINCIPAL },
    });
    if (!principalComment) {
      throw new BadRequestException("Missing PRINCIPAL comment");
    }
  }

  /**
   * Same FULL_TERM completeness rules as assertFullTermPublishGate (PRD
   * FR4.7), but batched across every student currently in a class arm and
   * non-throwing — lets Admin see, before generating anything, which
   * students already have every piece in place and which don't, instead of
   * discovering it one publish() rejection at a time.
   */
  async classReadiness(classArmId: string, termId: string): Promise<{ totalStudents: number; students: ClassReadinessEntry[] }> {
    const term = await this.prisma.term.findUniqueOrThrow({ where: { id: termId } });
    const students = await this.prisma.studentProfile.findMany({
      where: { currentClassId: classArmId },
      include: { user: true },
    });
    const studentIds = students.map((s) => s.id);

    const [enrollments, results, activeSkillItems, ratings, comments] = await Promise.all([
      this.prisma.studentSubjectEnrollment.findMany({
        where: { studentId: { in: studentIds }, classArmId, termId, status: EnrollmentStatus.ACTIVE },
      }),
      this.prisma.subjectTermResult.findMany({ where: { studentId: { in: studentIds }, termId } }),
      this.prisma.skillAssessmentItem.findMany({ where: { academicSessionId: term.academicSessionId, isActive: true } }),
      this.prisma.skillRating.findMany({ where: { studentId: { in: studentIds }, termId } }),
      this.prisma.reportComment.findMany({
        where: {
          studentId: { in: studentIds },
          termId,
          commentType: { in: [ReportCommentType.CLASS_TEACHER, ReportCommentType.PRINCIPAL] },
        },
      }),
    ]);

    const readiness = students.map((student): ClassReadinessEntry => {
      const missing: string[] = [];

      const missingSubjects = enrollments
        .filter((e) => e.studentId === student.id)
        .filter((e) => !results.some((r) => r.studentId === student.id && r.subjectId === e.subjectId));
      if (missingSubjects.length > 0) {
        missing.push(`Missing SubjectTermResult for ${missingSubjects.length} actively-enrolled subject(s)`);
      }

      const missingSkills = activeSkillItems.filter(
        (item) => !ratings.some((r) => r.studentId === student.id && r.skillAssessmentItemId === item.id),
      );
      if (missingSkills.length > 0) {
        missing.push(`Missing SkillRating for ${missingSkills.length} active skill assessment item(s)`);
      }

      const hasClassTeacherComment = comments.some(
        (c) => c.studentId === student.id && c.commentType === ReportCommentType.CLASS_TEACHER,
      );
      if (!hasClassTeacherComment) missing.push("Missing CLASS_TEACHER comment");

      const hasPrincipalComment = comments.some(
        (c) => c.studentId === student.id && c.commentType === ReportCommentType.PRINCIPAL,
      );
      if (!hasPrincipalComment) missing.push("Missing PRINCIPAL comment");

      return {
        studentId: student.id,
        studentName: `${student.user.firstName} ${student.user.lastName}`,
        ready: missing.length === 0,
        missing,
      };
    });

    return { totalStudents: students.length, students: readiness };
  }

  /**
   * Bulk trigger, not bulk generation: loops generateFullTerm() once per
   * ready student in the class (same explicit per-student upsert+enqueue as
   * the single-student flow, just called N times from one Admin action)
   * rather than introducing a separate batch code path. Students still
   * missing a piece per classReadiness are skipped, not force-generated —
   * generate one-off for those after filling the gap.
   */
  async generateForClass(dto: GenerateClassReportCardsDto, userId: string) {
    const { students } = await this.classReadiness(dto.classArmId, dto.termId);
    const ready = students.filter((s) => s.ready);
    const notReady = students.filter((s) => !s.ready);

    for (const student of ready) {
      await this.generateFullTerm({ studentId: student.studentId, termId: dto.termId }, userId);
    }

    return {
      generatedCount: ready.length,
      generatedStudentIds: ready.map((s) => s.studentId),
      skipped: notReady.map((s) => ({ studentId: s.studentId, studentName: s.studentName, missing: s.missing })),
    };
  }

  /**
   * PRD §5: Super-Admin/Admin see every report card regardless of status
   * (they're the ones who publish it); class/subject teacher (STAFF) see
   * their own class's cards, any status; parents see only their wards' and
   * students see only their own, both published-only — same row-level
   * scoping shape as StudentService.findAllForUser (identity/students/
   * student.ts), applied here to TermReportCard instead of StudentProfile.
   *
   * Non-admin roles compose an `OR` of whichever access paths this caller
   * actually holds, rather than an early-return priority chain — a
   * STAFF+PARENT user (e.g. a class teacher who also guardians a child) must
   * see their own child's card via the PARENT clause even though the STAFF
   * clause also runs (and typically doesn't cover that child's class), and
   * their homeroom's cards via the STAFF clause regardless of also being a
   * parent. Each clause keeps its own status filter (STAFF: any status;
   * PARENT/STUDENT: published-only).
   */
  async findForUser(user: RequestUser, filters: { studentId?: string; termId?: string; classArmId?: string }) {
    const { classArmId, ...scalarFilters } = filters;
    const studentSelect = {
      admissionNumber: true,
      user: { select: { firstName: true, lastName: true } },
      currentClass: { select: { name: true, classLevel: { select: { name: true } } } },
    } as const;

    if (user.roles.includes("SUPER_ADMIN") || user.roles.includes("ADMIN")) {
      const cards = await this.prisma.termReportCard.findMany({
        where: { ...scalarFilters, ...(classArmId ? { student: { currentClassId: classArmId } } : {}) },
        include: { student: { select: studentSelect } },
        orderBy: { createdAt: "desc" },
      });
      return cards.map(withStudentClassArmDisplayName);
    }

    const orConditions: Prisma.TermReportCardWhereInput[] = [];

    if (user.roles.includes("STAFF")) {
      // PRD §5: Principal/Headteacher hold a school-wide assignment, not a
      // per-class one — same carve-out StudentService.scopeWhereForUser
      // applies, otherwise they'd see zero report cards (no CLASS_TEACHER/
      // SUBJECT_TEACHER assignment to scope by).
      if (await this.staffAssignments.hasActiveSchoolWideAssignment(user.id)) {
        orConditions.push(classArmId ? { student: { currentClassId: classArmId } } : {});
      } else {
        // PRD §5: class/subject teacher see report cards for their own
        // class(es) — not published-only, unlike parent/student, since staff
        // may need to review a card before it's published. A requested
        // classArmId narrows within that assigned set (intersected, not
        // substituted) rather than trusting an arbitrary caller-supplied id.
        const assignedClassArmIds = await this.staffAssignments.activeAssignedClassArmIds(user.id);
        const scopedClassArmIds = classArmId
          ? assignedClassArmIds.filter((id) => id === classArmId)
          : assignedClassArmIds;
        if (scopedClassArmIds.length > 0) {
          orConditions.push({ student: { currentClassId: { in: scopedClassArmIds } } });
        }
      }
    }

    if (user.roles.includes("PARENT")) {
      const parentProfile = await this.prisma.parentProfile.findUnique({ where: { userId: user.id } });
      if (parentProfile) {
        orConditions.push({
          status: TermReportCardStatus.PUBLISHED,
          student: {
            guardians: { some: { parentId: parentProfile.id } },
            ...(classArmId ? { currentClassId: classArmId } : {}),
          },
        });
      }
    }

    if (user.roles.includes("STUDENT")) {
      const studentProfile = await this.prisma.studentProfile.findUnique({ where: { userId: user.id } });
      if (studentProfile && (!classArmId || studentProfile.currentClassId === classArmId)) {
        orConditions.push({ studentId: studentProfile.id, status: TermReportCardStatus.PUBLISHED });
      }
    }

    if (orConditions.length === 0) return [];

    const cards = await this.prisma.termReportCard.findMany({
      where: { ...scalarFilters, OR: orConditions },
      include: { student: { select: studentSelect } },
      orderBy: { createdAt: "desc" },
    });
    return cards.map(withStudentClassArmDisplayName);
  }

  async remove(id: string) {
    return this.prisma.termReportCard.delete({ where: { id } });
  }

  /**
   * Public verification lookup for the PDF's QR code (report-card.processor.ts,
   * apps/worker, mints the token/hash pair on every generation). Reachable
   * with no authentication — see ReportCardVerificationController below —
   * so this deliberately returns no scores, just enough to confirm the
   * document is genuine.
   */
  async verify(rawToken: string) {
    const reportCard = await this.prisma.termReportCard.findFirst({
      where: { verificationTokenHash: hashToken(rawToken) },
      include: {
        student: { include: { user: true, currentClass: { include: { classLevel: true } } } },
        term: { include: { academicSession: true } },
      },
    });

    if (!reportCard || reportCard.status !== TermReportCardStatus.PUBLISHED) {
      return { valid: false as const };
    }

    return {
      valid: true as const,
      studentName: `${reportCard.student.user.firstName} ${reportCard.student.user.lastName}`,
      admissionNumber: reportCard.student.admissionNumber,
      className: reportCard.student.currentClass
        ? `${reportCard.student.currentClass.classLevel.name} ${reportCard.student.currentClass.name}`
        : null,
      termName: reportCard.term.name,
      sessionName: reportCard.term.academicSession.name,
      reportType: reportCard.reportType,
      generatedAt: reportCard.generatedAt,
      publishedAt: reportCard.publishedAt,
    };
  }

  // Same shape as ReportCommentService.progress (assessments/report-comment.ts)
  // — totalStudents is everyone currently in the arm (or, with
  // academicSessionId instead of classArmId, everyone in the session — the
  // dashboard's session-wide publish-rate widget needs the sum across every
  // arm, not a per-arm breakdown, so this avoids the N-requests-per-arm fan
  // out that used to require), generatedCount is distinct students with at
  // least one report card for the term (either reportType), so it reflects
  // "does this student have something on file", not raw row count (a student
  // can hold both a MID_TERM and FULL_TERM row).
  async progress(filters: { classArmId?: string; academicSessionId?: string; termId: string }) {
    if (!filters.classArmId && !filters.academicSessionId) {
      throw new BadRequestException("classArmId or academicSessionId is required");
    }
    const studentWhere = filters.classArmId
      ? { currentClassId: filters.classArmId }
      : { currentClass: { academicSessionId: filters.academicSessionId } };
    const [totalStudents, generatedStudents] = await Promise.all([
      this.prisma.studentProfile.count({ where: studentWhere }),
      this.prisma.termReportCard.findMany({
        where: { termId: filters.termId, student: studentWhere },
        select: { studentId: true },
        distinct: ["studentId"],
      }),
    ]);
    return { totalStudents, generatedCount: generatedStudents.length };
  }
}

@Controller("term-report-cards")
@UseGuards(JwtAuthGuard, PoliciesGuard)
export class TermReportCardController {
  constructor(private readonly service: TermReportCardService) {}

  @Post("generate")
  @CheckPolicies((ability) => ability.can("manage", "TermReportCard"))
  generate(@Body() dto: GenerateTermReportCardDto, @CurrentUser() user: RequestUser) {
    return this.service.generateFullTerm(dto, user.id);
  }

  @Get("class-readiness")
  @CheckPolicies((ability) => ability.can("manage", "TermReportCard"))
  classReadiness(@Query("classArmId") classArmId: string, @Query("termId") termId: string) {
    return this.service.classReadiness(classArmId, termId);
  }

  @Post("generate-class")
  @CheckPolicies((ability) => ability.can("manage", "TermReportCard"))
  generateClass(@Body() dto: GenerateClassReportCardsDto, @CurrentUser() user: RequestUser) {
    return this.service.generateForClass(dto, user.id);
  }

  @Get()
  findAll(
    @CurrentUser() user: RequestUser,
    @Query("studentId") studentId?: string,
    @Query("termId") termId?: string,
    @Query("classArmId") classArmId?: string,
  ) {
    return this.service.findForUser(user, { studentId, termId, classArmId });
  }

  @Get("progress")
  progress(
    @Query("classArmId") classArmId: string | undefined,
    @Query("academicSessionId") academicSessionId: string | undefined,
    @Query("termId") termId: string,
  ) {
    return this.service.progress({ classArmId, academicSessionId, termId });
  }

  @Patch(":id/regenerate")
  @CheckPolicies((ability) => ability.can("manage", "TermReportCard"))
  regenerate(@Param("id") id: string) {
    return this.service.regenerate(id);
  }

  @Patch(":id/publish")
  @CheckPolicies((ability) => ability.can("manage", "TermReportCard"))
  publish(@Param("id") id: string) {
    return this.service.publish(id);
  }

  @Delete(":id")
  remove(@Param("id") id: string, @CurrentUser() user: RequestUser) {
    // Super-Admin-only carve-out, not a plain CASL "manage" check — Admin
    // already has "manage" on TermReportCard (generate/publish), but
    // deleting a generated report card is reserved for the owner, same
    // pattern as the owner-only check in identity/ownership-transfer.ts.
    if (!user.roles.includes("SUPER_ADMIN")) {
      throw new ForbiddenException("Only the Super-Admin can delete a report card");
    }
    return this.service.remove(id);
  }
}

/**
 * Deliberately separate from TermReportCardController, which carries a
 * class-level @UseGuards(JwtAuthGuard, PoliciesGuard) — this codebase has no
 * @Public()-style guard bypass, so a route that must work with no login
 * (scanning a report card's QR code) needs its own unguarded controller
 * rather than an exception carved into the guarded one.
 */
@Controller("term-report-cards/verify")
export class ReportCardVerificationController {
  constructor(private readonly service: TermReportCardService) {}

  @Get(":token")
  verify(@Param("token") token: string) {
    return this.service.verify(token);
  }
}
